name: Lint and Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths:
      - 'lib/**'
      - 'test/**'

jobs:
  lint:
    name: Analysis
    runs-on: ubuntu-latest
    container:
      image: docker://yumoose/flutter-fire:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run analysis
        run: flutter analyze

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    container:
      image: docker://yumoose/flutter-fire:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage/lcov.info
